import React, { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Circle, ClipboardList, LogOut, Pencil, Plus, Search, Trash2, X } from 'lucide-react';

const API = import.meta.env.VITE_API_URL || 'http://localhost:5000/api';
const emptyForm = { title:'', description:'', priority:'Medium', status:'Pending', dueDate:'' };

async function api(path, options={}) {
  const token = localStorage.getItem('task_token');
  const res = await fetch(`${API}${path}`, { ...options, headers:{'Content-Type':'application/json', ...(token?{Authorization:`Bearer ${token}`}:{}) , ...(options.headers||{})} });
  const data = await res.json().catch(()=>({}));
  if (!res.ok) throw new Error(data.message || 'Something went wrong');
  return data;
}

function Auth({ onLogin }) {
  const [register,setRegister]=useState(false); const [form,setForm]=useState({name:'',email:'',password:''}); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const submit=async e=>{e.preventDefault();setError('');setBusy(true);try{const data=await api(`/auth/${register?'register':'login'}`,{method:'POST',body:JSON.stringify(form)});localStorage.setItem('task_token',data.token);localStorage.setItem('task_user',JSON.stringify(data.user));onLogin(data.user)}catch(err){setError(err.message)}finally{setBusy(false)}};
  return <main className="auth-page"><div className="auth-card"><div className="brand"><div className="brand-icon"><ClipboardList/></div><div><h1>TaskFlow</h1><p>Simple task management</p></div></div><h2>{register?'Create your account':'Welcome back'}</h2><p className="muted">{register?'Start organizing your work today.':'Log in to manage your tasks.'}</p><form onSubmit={submit}>{register&&<label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Your name" required/></label>}<label>Email<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com" required/></label><label>Password<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="At least 6 characters" required/></label>{error&&<div className="error">{error}</div>}<button className="primary full" disabled={busy}>{busy?'Please wait…':register?'Create account':'Log in'}</button></form><button className="link-btn" onClick={()=>{setRegister(!register);setError('')}}>{register?'Already have an account? Log in':'New here? Create an account'}</button></div></main>
}

function TaskModal({ task, onClose, onSave }) {
  const [form,setForm]=useState(task?{...task,dueDate:task.dueDate?task.dueDate.slice(0,10):''}:emptyForm); const [error,setError]=useState('');
  const submit=async e=>{e.preventDefault();if(!form.title.trim())return setError('Task title is required');try{await onSave({...form,title:form.title.trim()})}catch(err){setError(err.message)}};
  return <div className="overlay"><div className="modal"><div className="modal-head"><div><h2>{task?'Edit task':'Create task'}</h2><p className="muted">Keep your work organized.</p></div><button className="icon-btn" onClick={onClose}><X/></button></div><form onSubmit={submit}><label>Task title<input autoFocus value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Complete project report"/></label><label>Description<textarea rows="4" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Add some details…"/></label><div className="form-grid"><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>Low</option><option>Medium</option><option>High</option></select></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Pending</option><option>In Progress</option><option>Completed</option></select></label></div><label>Due date<input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label>{error&&<div className="error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">{task?'Save changes':'Add task'}</button></div></form></div></div>
}

function Dashboard({user,onLogout}) {
 const [tasks,setTasks]=useState([]);const [loading,setLoading]=useState(true);const [modal,setModal]=useState(null);const [query,setQuery]=useState('');const [filter,setFilter]=useState('All');const [error,setError]=useState('');
 const load=async()=>{try{setTasks(await api('/tasks'))}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>tasks.filter(t=>(filter==='All'||t.status===filter)&&(`${t.title} ${t.description}`.toLowerCase().includes(query.toLowerCase()))),[tasks,filter,query]);
 const save=async data=>{if(modal==='new'){const created=await api('/tasks',{method:'POST',body:JSON.stringify(data)});setTasks([created,...tasks])}else{const updated=await api(`/tasks/${modal._id}`,{method:'PUT',body:JSON.stringify(data)});setTasks(tasks.map(t=>t._id===updated._id?updated:t))}setModal(null)};
 const remove=async id=>{if(!confirm('Delete this task?'))return;try{await api(`/tasks/${id}`,{method:'DELETE'});setTasks(tasks.filter(t=>t._id!==id))}catch(e){setError(e.message)}};
 const toggle=async t=>{try{const updated=await api(`/tasks/${t._id}`,{method:'PUT',body:JSON.stringify({status:t.status==='Completed'?'Pending':'Completed'})});setTasks(tasks.map(x=>x._id===updated._id?updated:x))}catch(e){setError(e.message)}};
 const stats={total:tasks.length,pending:tasks.filter(t=>t.status==='Pending').length,progress:tasks.filter(t=>t.status==='In Progress').length,done:tasks.filter(t=>t.status==='Completed').length};
 return <div className="app"><header><div className="header-inner"><div className="brand small"><div className="brand-icon"><ClipboardList/></div><div><h1>TaskFlow</h1><span>Task Management</span></div></div><div className="user-area"><span>Hello, <b>{user.name}</b></span><button className="logout" onClick={onLogout}><LogOut/> Logout</button></div></div></header><main className="dashboard"><div className="hero"><div><p className="eyebrow">YOUR WORKSPACE</p><h2>My Tasks</h2><p className="muted">Create, organize and track your work.</p></div><button className="primary" onClick={()=>setModal('new')}><Plus/> New task</button></div>{error&&<div className="error banner">{error}<button onClick={()=>setError('')}>×</button></div>}<div className="stats"><div><span>Total</span><strong>{stats.total}</strong></div><div><span>Pending</span><strong>{stats.pending}</strong></div><div><span>In progress</span><strong>{stats.progress}</strong></div><div><span>Completed</span><strong>{stats.done}</strong></div></div><div className="toolbar"><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tasks…"/></div><div className="filters">{['All','Pending','In Progress','Completed'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div></div>{loading?<div className="empty">Loading tasks…</div>:filtered.length===0?<div className="empty"><ClipboardList/><h3>No tasks found</h3><p>{tasks.length?'Try changing your search or filter.':'Create your first task to get started.'}</p>{!tasks.length&&<button className="primary" onClick={()=>setModal('new')}><Plus/> Create task</button>}</div>:<div className="task-list">{filtered.map(t=><article className={`task-card ${t.status==='Completed'?'completed':''}`} key={t._id}><button className="check" onClick={()=>toggle(t)} title="Toggle complete">{t.status==='Completed'?<CheckCircle2/>:<Circle/>}</button><div className="task-main"><div className="task-top"><h3>{t.title}</h3><span className={`priority ${t.priority.toLowerCase()}`}>{t.priority}</span></div>{t.description&&<p>{t.description}</p>}<div className="meta"><span className={`status ${t.status.toLowerCase().replace(' ','-')}`}>{t.status}</span>{t.dueDate&&<span>Due {new Date(t.dueDate).toLocaleDateString()}</span>}</div></div><div className="actions"><button onClick={()=>setModal(t)}><Pencil/></button><button onClick={()=>remove(t._id)}><Trash2/></button></div></article>)}</div>}</main>{modal&&<TaskModal task={modal==='new'?null:modal} onClose={()=>setModal(null)} onSave={save}/>}</div>
}

export default function App(){const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('task_user')||'null'));const logout=()=>{localStorage.removeItem('task_token');localStorage.removeItem('task_user');setUser(null)};return user?<Dashboard user={user} onLogout={logout}/>:<Auth onLogin={setUser}/>}
